language: node_js

node_js:
  - node

dist: bionic
sudo: required

branches:
  only:
  - routing

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://scibin.github.io/day06workshop/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/day06workshop
  on:
    branch: routing